version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    image: xferax/flask-app:1.2
    environment:
      - FLASK_APP=main_score.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./Scores.txt:/app/Scores.txt
